const RESPONSE = {
    ALL_FIELDS_REQUIRED: "Please fill in all the fields",
    EMAIL_ALREADY_REGISTERED: "This email is already registered",
    MOBILE_ALREADY_REGISTERED: "This mobile number is already registered",
    INVALID_OTP: "Invalid OTP",
    REGISTRATION_FAILED: "Registration Failed",
    INCORRECT_OTP: "Incorrect OTP. Please try again.",
    OTP_RESENT: "OTP resent successfully",
    OTP_SEND_FAILED: "Failed to send OTP",
    ACCOUNT_BLOCKED: "Your account is blocked.",
    USER_NOT_FOUND: "User not found",
    INCORRECT_PASSWORD: "Password is incorrect",
    VERIFY_EMAIL: "Please verify your mail",
    INVALID_SESSION: "Invalid or expired session",
    INSUFFICIENT_STOCK: "Insufficient stock",
    PRICE_RANGE_REQUIRED: "Minimum and maximum prices are required",
    PRICE_RANGE_NOT_FOUND: "Price range not found",
    INVALID_IDS: "Invalid userId or productId",
    PRODUCT_ALREADY_IN_WISHLIST: "Product already in wishlist",
    PRODUCT_ADDED: "Product added to the wishlist successfully",
    WISHLIST_NOT_FOUND: "Wishlist not found",
    PRODUCT_REMOVED: "Product removed from the wishlist successfully",
    USER_ID_MISSING: "User ID is missing",
    PRODUCT_NOT_FOUND: "Product not found",
    ERROR_ADDING_PRODUCT: "Error while adding product",
    IMAGE_REMOVAL_FAILED: "Failed to remove image",
    IMAGE_REMOVED: "Image removed successfully",
    ORDER_NOT_FOUND: "Order not found",
    CART_NOT_FOUND: "Cart not found",
    ALREADY_CANCELLED: "Order is already cancelled",
    DELIVERED_ORDER: "Cannot cancel a delivered order",
    CANCEL_TIME_EXCEEDED: "Cannot cancel an order placed for more than 10 days",
    ADDRESS_NOT_SELECTED: "Billing address not selected",
    INSUFFICIENT_WALLET_BALANCE: "Insufficient balance in wallet",
    INVALID_PAYMENT_METHOD: "Invalid payment method or an error occurred while placing the order",
    COUPON_NOT_FOUND: "Coupon not found",
    COUPON_EXPIRED: "Coupon Expired",
    COUPON_LIMIT_REACHED: "Coupon limit Reached",
    COUPON_ALREADY_USED: "You already used this coupon",
    COUPON_MIN_AMOUNT: "The amount is less than minimum amount",
    COUPON_MAX_AMOUNT: "The Discount cant be applied. It is beyond maximum amount",
    PAYMENT_FAILED: "Payment Failed",
    ORDER_PLACED: "Order placed successfully",
    COUPON_APPLIED: "Coupon applied successfully",
    OFFER_NOT_FOUND: "Offer not found",
    DUPLICATE_OFFER_NAME: "Duplicate Discount Name not allowed",
    CATEGORY_OFFER_EXISTS: "An offer for this category already exists",
    PRODUCT_OFFER_EXISTS: "An offer for this product already exists",
    FAILED_TO_UPDATE_OFFER: "Failed to update offer",
    COUPON_EXISTS: "Coupon code already exists",
    REQUIRED_FIELDS_MISSING: "Required fields missing",
    COUPON_ADDED: "Coupon added successfully",
    COUPON_UPDATED: "Coupon updated successfully",
    FAILED_TO_ADD_COUPON: "Failed to add coupon",
    FAILED_TO_UPDATE_COUPON: "Failed to update coupon",
    CATEGORY_EXISTS: "Category with the same name already exists",
    CATEGORY_NOT_FOUND: "Category not found",
    BANNER_NOT_FOUND: "Banner not found",
    BANNER_EXISTS: "Banner already exists",
    INVALID_REQUEST: "Invalid request data",
    ORDER_ID_MISSING: "Order ID is missing",
    ERROR_FETCHING_ORDERS: "Error fetching orders",
    ADMIN_NOT_FOUND: "Admin not found",
    PASSWORD_INCORRECT: "Password is incorrect",
    NOT_ADMIN: "Not an admin",
    ADDRESS_NOT_FOUND: "Address not found",
    SERVER_ERROR:"Internal Server Error"
  };
  
  module.exports = RESPONSE;